version: 2.1

executors:
  default_container:
    docker:
      - image: circleci/ruby:2.6.1-node
        environment:
          RAILS_ENV: test
          BUNDLE_JOBS: 4
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          BUNDLER_VERSION: 2.0.1
          BUNDLE_FLAGS: --clean

      - image: circleci/mysql:latest
        command: mysqld --default-authentication-plugin=mysql_native_password
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
    working_directory: ~/qiita_clone_2019

commands:
  install_bundler:
    description: Bundlerのインストール
    steps:
      - run: gem install bundler -v 2.0.1


jobs:
  fetch_source_code:
    executor:
      name: default_container
    steps:
      - checkout
      - save_cache:
          key: v3-qiita_clone_2019-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/qiita_clone_2019

  bundle_dependencies:
    executor:
      name: default_container
    steps:
      - restore_cache: # ソースコードの復元
          key: v3-qiita_clone_2019-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache: # vendor/bundleを復元
          key: v3-dependencies-{{ checksum "Gemfile.lock" }}

      - run:
          name: setup bundler
          command: |
            sudo gem uninstall bundler
            sudo rm /usr/local/bin/bundle
            sudo rm /usr/local/bin/bundler
            sudo gem install bundler -v 2.0.1

      - run:
          name: Bundle Install Dependencies
          command: |
            bundle install

      - save_cache:
          key: v3-dependencies-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

  rubocop:
    executor:
      name: default_container
    steps:
      - restore_cache: # ソースコードの復元
          key: v3-qiita_clone_2019-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache: # vendor/bundleを復元
          key: v3-dependencies-{{ checksum "Gemfile.lock" }}
      - install_bundler
      - run:
          name: Execute rubocop
          command: |
            bundle exec rubocop

  rspec:
    executor:
      name: default_container
    steps:
      - restore_cache: # ソースコードの復元
          key: v3-qiita_clone_2019-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache: # vendor/bundleを復元
          key: v3-dependencies-{{ checksum "Gemfile.lock" }}

      - run:
          name: Watting stand up database
          command: |
            dockerize -wait \
            tcp://127.0.0.1:3306 -timeout 120s

      # Database setup
      - run: mv ./config/database.yml.ci ./config/database.yml
      - install_bundler
      - run:
          name: Testing DB migration and seed
          command: |
            bundle exec rails db:create db:migrate db:seed db:drop

      # mkdir directory for upload test results
      - run: mkdir /tmp/test-results
      - run: mkdir -p ~/rspec

      # run tests!
      - run:
          name: Run rspec
          command: |
            bundle exec rails db:create db:migrate
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)"
            bundle exec rspec --require rails_helper \
                              --color \
                              --format progress \
                              --format RspecJunitFormatter \
                              --out ~/rspec/rspec.xml

      # collect reports
      - store_test_results:
          path: ~/rspec
      - store_artifacts:
          path: ~/tmp/test-results
          destination: test-results

  deploy_by_capistrano:
    executor:
      name: default_container
    steps:
      - restore_cache: # ソースコードの復元
          key: v3-qiita_clone_2019-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache: # vendor/bundleを復元
          key: v3-dependencies-{{ checksum "Gemfile.lock" }}
      - install_bundler
      - deploy:
          name: deploy by capistrano
          command: |
            bundle install --clean
            bundle exec cap production deploy


workflows:
  build:
    jobs:
      - fetch_source_code
      - bundle_dependencies:
          requires:
            - fetch_source_code
      - rubocop:
          requires: # bundle_dependenciesの後にrubocopを実行する
            - bundle_dependencies
      - rspec:
          requires: # bundle_dependenciesの後にrspecを実行する
            - bundle_dependencies
      - deploy_by_capistrano:
          requires: # すべてのテスト実行後にdeployを行う
            - rubocop
            - rspec
          filters: # masterブランチのみdeployを行う
            branches:
              only: feature/deploy_by_circleci
